-- return {
--     "rcarriga/nvim-dap-ui",
--     opt = true,
--     event = "BufReadPre",
--     requires = {
--         "mfussenegger/nvim-dap"
--     },
--     config = function()
--         require("dapui").setup()
--     end,
-- }
